name: Docker Build & Run

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build  -f nginx -t my-app:latest .

      - name: Run Docker image
        run: docker run -d --name my-nginx -p 8080:80 my-app:latest
